### PR TITLE
doc(readme_fr_FR) : add info about event triggering and handling

### PR DESCRIPTION
**Pull request by forresst**
ref  #133 and typo readme.md

### CODE REVIEW

**Comment by forresst** [comment]
@petebacondarwin to branch hooks. 

I would be ahead for once :smile:

**Comment by forresst** [comment]
cc @petebacondarwin Can you merge https://github.com/forresst/dgeni/commit/f708a82fbbea538916b8b09fd7682a3ffb484a55 ?

**Comment by forresst** [comment]
Yes i signed !

**Comment by petebacondarwin** [comment]
Will do

**Comment by forresst** [comment]
:+1:

**Pull request closed without merging**
