### PR TITLE
Bump winston dependency to avoid brining in deps that require node 0.8.x

### LINKED ISSUE #126: lower version of winston occurs 'node version error' with node.js 0.10.x
Currently the sntp of the hawk of the request of winston seems like a suspect.

### PR DESCRIPTION
**Pull request by keirlawson**
Fixes #126, also bump minor version number as this constitutes a breaking change as winston is exposed.

### CODE REVIEW

**Comment by keirlawson** [comment]
I am the author of this change and have signed the CLA, however it doesn't seem to be picking up the secondary email address that happens to be on the commit message.

**Comment by petebacondarwin** [comment]
Thanks @keirlawson

I am not sure if this should count as a breaking change.

I looked through the logs of the changes from 0.7.2 to 1.1.2 and the breaking changes do not affect the way that we use logging in dgeni - i.e. although we expose the `winston` object, it is never described publicly as winston and the expected usage was always only setting the level and then calling one of the logging methods.

That being said, I have #133 and #134 waiting to land. Perhaps we should polish those up and bump to 0.5.0 along with this change.

**Comment by keirlawson** [comment]
Ok have removed bumping the dgeni version from this PR so that can be done separate whenever it makes sense.

**Comment by petebacondarwin** [comment]
Thanks @keirlawson - landed with a tweak to the commit message text

**Pull request closed without merging**
