### PR TITLE
Updated dependencies versions

### PR DESCRIPTION
**Pull request by ivorobkalo**
With updated dependencies tests still pass.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Great. Thanks!

**Comment by petebacondarwin** [comment]
@ivorobkalo can you please sign the CLA?

**Comment by ivorobkalo** [comment]
I think I signed it just right after a pull request as googlebot asked me to do.

**Comment by petebacondarwin** [comment]
Can you add a comment saying "I signed it" to trigger the bot to check?

**Comment by ivorobkalo** [comment]
I signed it

**Pull request closed without merging**
